In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# (My Code from ITMD 522 - HW#2)

# import pandas as pd.
import pandas as pd
import numpy as np
from pathlib import Path

# Folder path: '/Users/harshpatel/Desktop/MS-ITM/ITMD 524/project_dataset'
folder_path = Path('/Users/harshpatel/Desktop/MS-ITM/ITMD 524/project_dataset')  

# Read the excel file and specific 'Data' spreadsheet from CSV file. Get all CSV files in the folder.
# pandas.read_csv(filepath_or_buffer, *, sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=<no_default>, skip_blank_lines=True, parse_dates=None, infer_datetime_format=<no_default>, keep_date_col=<no_default>, date_parser=<no_default>, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=<no_default>, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=<no_default>)
# csv_files = [f for f in folder_path.glob('*.csv') if 'Small' in f.name]
csv_files = [f for f in folder_path.glob('*.csv') if 'Small' in f.name]

# To assign names for each datafile as a dataframe.
for file in csv_files:
    var_name = file.stem.replace(" ", "_").replace("-", "_")
    globals()[var_name] = pd.read_csv(file)
    print(f"Loaded: {var_name} (shape: {globals()[var_name].shape})")

Loaded: HI_Small_Trans (shape: (5078345, 11))
Loaded: LI_Small_Trans (shape: (6924049, 11))

# HI_Small_Trans dataset.

In [3]:
LI_Small_Trans

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:08,11,8000ECA90,11,8000ECA90,3.195403e+06,US Dollar,3.195403e+06,US Dollar,Reinvestment,0
1,2022/09/01 00:21,3402,80021DAD0,3402,80021DAD0,1.858960e+03,US Dollar,1.858960e+03,US Dollar,Reinvestment,0
2,2022/09/01 00:00,11,8000ECA90,1120,8006AA910,5.925710e+05,US Dollar,5.925710e+05,US Dollar,Cheque,0
3,2022/09/01 00:16,3814,8006AD080,3814,8006AD080,1.232000e+01,US Dollar,1.232000e+01,US Dollar,Reinvestment,0
4,2022/09/01 00:00,20,8006AD530,20,8006AD530,2.941560e+03,US Dollar,2.941560e+03,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
6924044,2022/09/10 23:39,71696,81B2518F1,71528,81C0482E1,3.346900e-02,Bitcoin,3.346900e-02,Bitcoin,Bitcoin,0
6924045,2022/09/10 23:48,271241,81B567481,173457,81C0DA751,1.313000e-03,Bitcoin,1.313000e-03,Bitcoin,Bitcoin,0
6924046,2022/09/10 23:50,271241,81B567481,173457,81C0DA751,1.305800e-02,Bitcoin,1.305800e-02,Bitcoin,Bitcoin,0
6924047,2022/09/10 23:57,170558,81A2206B1,275798,81C1D5CA1,4.145370e-01,Bitcoin,4.145370e-01,Bitcoin,Bitcoin,0
6924048,2022/09/10 23:31,170558,81A2206B1,275798,81C1D5CA1,3.427700e-02,Bitcoin,3.427700e-02,Bitcoin,Bitcoin,0

# LI_Small_Trans dataset.

In [4]:
HI_Small_Trans

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0

# Merge two dataset.

In [5]:
merged_Small_df = pd.concat([LI_Small_Trans, HI_Small_Trans], ignore_index=True)
display(merged_Small_df)
display(merged_Small_df.info())
display(merged_Small_df.nunique())
value_counts = merged_Small_df['Is Laundering'].value_counts()
print(value_counts)

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:08,11,8000ECA90,11,8000ECA90,3.195403e+06,US Dollar,3.195403e+06,US Dollar,Reinvestment,0
1,2022/09/01 00:21,3402,80021DAD0,3402,80021DAD0,1.858960e+03,US Dollar,1.858960e+03,US Dollar,Reinvestment,0
2,2022/09/01 00:00,11,8000ECA90,1120,8006AA910,5.925710e+05,US Dollar,5.925710e+05,US Dollar,Cheque,0
3,2022/09/01 00:16,3814,8006AD080,3814,8006AD080,1.232000e+01,US Dollar,1.232000e+01,US Dollar,Reinvestment,0
4,2022/09/01 00:00,20,8006AD530,20,8006AD530,2.941560e+03,US Dollar,2.941560e+03,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
12002389,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,1.549780e-01,Bitcoin,1.549780e-01,Bitcoin,Bitcoin,0
12002390,2022/09/10 23:35,15,8148A8671,256398,8148A8711,1.081280e-01,Bitcoin,1.081280e-01,Bitcoin,Bitcoin,0
12002391,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,4.988000e-03,Bitcoin,4.988000e-03,Bitcoin,Bitcoin,0
12002392,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,3.841700e-02,Bitcoin,3.841700e-02,Bitcoin,Bitcoin,0
12002393,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,2.819830e-01,Bitcoin,2.819830e-01,Bitcoin,Bitcoin,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12002394 entries, 0 to 12002393
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Timestamp           object
 1   From Bank           int64
 2   Account             object
 3   To Bank             int64
 4   Account.1           object
 5   Amount Received     float64
 6   Receiving Currency  object
 7   Amount Paid         float64
 8   Payment Currency    object
 9   Payment Format      object
 10  Is Laundering       int64
dtypes: float64(2), int64(3), object(6)
memory usage: 1007.3+ MB

None

Timestamp               15133
From Bank               57222
Account               1166980
To Bank                 33608
Account.1              988911
Amount Received       1835635
Receiving Currency         15
Amount Paid           1850741
Payment Currency           15
Payment Format              7
Is Laundering               2
dtype: int64

0    11993652
1        8742
Name: Is Laundering, dtype: int64

# X independent and Y dependent variable.

In [6]:
# Define a function to extract last 4 characters from account (as string)
def last_4_digits(val):
    if pd.isna(val):
        return 'UNK'  # For missing values
    return str(val)[-4:]

# Apply it to high-cardinality object columns
merged_Small_df['Account_Grouped'] = merged_Small_df['Account'].apply(last_4_digits)
merged_Small_df['Account1_Grouped'] = merged_Small_df['Account.1'].apply(last_4_digits)

X = merged_Small_df.drop(columns='Is Laundering')
y = merged_Small_df['Is Laundering']

print("X:\n")
display(X)

print("Y:\n")
display(y)

X:

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Account_Grouped,Account1_Grouped
0,2022/09/01 00:08,11,8000ECA90,11,8000ECA90,3.195403e+06,US Dollar,3.195403e+06,US Dollar,Reinvestment,CA90,CA90
1,2022/09/01 00:21,3402,80021DAD0,3402,80021DAD0,1.858960e+03,US Dollar,1.858960e+03,US Dollar,Reinvestment,DAD0,DAD0
2,2022/09/01 00:00,11,8000ECA90,1120,8006AA910,5.925710e+05,US Dollar,5.925710e+05,US Dollar,Cheque,CA90,A910
3,2022/09/01 00:16,3814,8006AD080,3814,8006AD080,1.232000e+01,US Dollar,1.232000e+01,US Dollar,Reinvestment,D080,D080
4,2022/09/01 00:00,20,8006AD530,20,8006AD530,2.941560e+03,US Dollar,2.941560e+03,US Dollar,Reinvestment,D530,D530
...,...,...,...,...,...,...,...,...,...,...,...,...
12002389,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,1.549780e-01,Bitcoin,1.549780e-01,Bitcoin,Bitcoin,6631,8711
12002390,2022/09/10 23:35,15,8148A8671,256398,8148A8711,1.081280e-01,Bitcoin,1.081280e-01,Bitcoin,Bitcoin,8671,8711
12002391,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,4.988000e-03,Bitcoin,4.988000e-03,Bitcoin,Bitcoin,6771,8711
12002392,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,3.841700e-02,Bitcoin,3.841700e-02,Bitcoin,Bitcoin,6311,8711
12002393,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,2.819830e-01,Bitcoin,2.819830e-01,Bitcoin,Bitcoin,6091,8711

Y:

0           0
1           0
2           0
3           0
4           0
           ..
12002389    0
12002390    0
12002391    0
12002392    0
12002393    0
Name: Is Laundering, Length: 12002394, dtype: int64

# Things I did for X.

- Convert Timestamp into columns like i.e., {hour, day, weekday, and month}.
- For Account_Grouped and Account1_Grouped columns,
    - Extract first two letters (if present)
    - Collect the digits at the end (whatever part is numeric)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import re

X = X.drop(columns=['Account', 'Account.1'])

# Convert string to datetime
X['timestamp_column_name'] = pd.to_datetime(X['Timestamp'])

# Extract useful numeric features
X['hour'] = X['timestamp_column_name'].dt.hour
X['day'] = X['timestamp_column_name'].dt.day
X['weekday'] = X['timestamp_column_name'].dt.weekday
X['month'] = X['timestamp_column_name'].dt.month

X = X.drop(['Timestamp'], axis=1)

categorical_cols = ['Receiving Currency', 'Payment Currency', 'Payment Format']

encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
encoded_array = encoder.fit_transform(X[categorical_cols])

encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(categorical_cols),
    index=X.index  # preserve index for joining later
)

X = pd.concat([X.drop(columns=categorical_cols), encoded_df], axis=1)

import re

def encode_account_grouped_flexible(val):
    val = str(val).strip()
    
    # Extract all letters and digits separately
    letters = ''.join(re.findall(r'[A-Za-z]', val))
    digits_str = ''.join(re.findall(r'\d+', val))  # Collect only digits

    # Default: handle at most 2 letters
    l1 = ord(letters[0].upper()) - ord('A') if len(letters) >= 1 else -1
    l2 = ord(letters[1].upper()) - ord('A') if len(letters) >= 2 else -1

    try:
        digits = int(digits_str)
    except ValueError:
        digits = -1  # fallback if digits can't be parsed

    return pd.Series({'AG_L1': l1, 'AG_L2': l2, 'AG_Num': digits})


X[['AG_L1', 'AG_L2', 'AG_Num']] = X['Account_Grouped'].apply(encode_account_grouped_flexible)
X[['AG1_L1', 'AG1_L2', 'AG1_Num']] = X['Account1_Grouped'].apply(encode_account_grouped_flexible)
X.drop(columns=['Account_Grouped', 'Account1_Grouped'], inplace=True)

X

/usr/local/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,From Bank,To Bank,Amount Received,Amount Paid,timestamp_column_name,hour,day,weekday,month,Receiving Currency_Australian Dollar,...,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num
0,11,11,3.195403e+06,3.195403e+06,2022-09-01 00:08:00,0,1,3,9,0.0,...,0.0,0.0,1.0,0.0,2,0,90,2,0,90
1,3402,3402,1.858960e+03,1.858960e+03,2022-09-01 00:21:00,0,1,3,9,0.0,...,0.0,0.0,1.0,0.0,3,0,0,3,0,0
2,11,1120,5.925710e+05,5.925710e+05,2022-09-01 00:00:00,0,1,3,9,0.0,...,1.0,0.0,0.0,0.0,2,0,90,0,-1,910
3,3814,3814,1.232000e+01,1.232000e+01,2022-09-01 00:16:00,0,1,3,9,0.0,...,0.0,0.0,1.0,0.0,3,-1,80,3,-1,80
4,20,20,2.941560e+03,2.941560e+03,2022-09-01 00:00:00,0,1,3,9,0.0,...,0.0,0.0,1.0,0.0,3,-1,530,3,-1,530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12002389,54219,256398,1.549780e-01,1.549780e-01,2022-09-10 23:57:00,23,10,5,9,0.0,...,0.0,0.0,0.0,0.0,-1,-1,6631,-1,-1,8711
12002390,15,256398,1.081280e-01,1.081280e-01,2022-09-10 23:35:00,23,10,5,9,0.0,...,0.0,0.0,0.0,0.0,-1,-1,8671,-1,-1,8711
12002391,154365,256398,4.988000e-03,4.988000e-03,2022-09-10 23:52:00,23,10,5,9,0.0,...,0.0,0.0,0.0,0.0,-1,-1,6771,-1,-1,8711
12002392,256398,256398,3.841700e-02,3.841700e-02,2022-09-10 23:46:00,23,10,5,9,0.0,...,0.0,0.0,0.0,0.0,-1,-1,6311,-1,-1,8711
12002393,154518,256398,2.819830e-01,2.819830e-01,2022-09-10 23:37:00,23,10,5,9,0.0,...,0.0,0.0,0.0,0.0,-1,-1,6091,-1,-1,8711

In [8]:
y

0           0
1           0
2           0
3           0
4           0
           ..
12002389    0
12002390    0
12002391    0
12002392    0
12002393    0
Name: Is Laundering, Length: 12002394, dtype: int64

# Now, Oversample (SMOTE) and Undersample Majority Class.

- We will get new balanced data -- X and y.

In [9]:
# Identify datetime columns
datetime_cols = X.select_dtypes(include=['datetime64']).columns
print(datetime_cols)

# Convert them into numeric features (like year, month, etc.)
for col in datetime_cols:
    X[f'{col}_year'] = X[col].dt.year
    X[f'{col}_month'] = X[col].dt.month
    X[f'{col}_day'] = X[col].dt.day
    X[f'{col}_minute'] = X[col].dt.minute
    # drop original datetime column
    X.drop(columns=col, inplace=True)
    
X

Index(['timestamp_column_name'], dtype='object')

,From Bank,To Bank,Amount Received,Amount Paid,hour,day,weekday,month,Receiving Currency_Australian Dollar,Receiving Currency_Bitcoin,...,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num,timestamp_column_name_year,timestamp_column_name_month,timestamp_column_name_day,timestamp_column_name_minute
0,11,11,3.195403e+06,3.195403e+06,0,1,3,9,0.0,0.0,...,2,0,90,2,0,90,2022,9,1,8
1,3402,3402,1.858960e+03,1.858960e+03,0,1,3,9,0.0,0.0,...,3,0,0,3,0,0,2022,9,1,21
2,11,1120,5.925710e+05,5.925710e+05,0,1,3,9,0.0,0.0,...,2,0,90,0,-1,910,2022,9,1,0
3,3814,3814,1.232000e+01,1.232000e+01,0,1,3,9,0.0,0.0,...,3,-1,80,3,-1,80,2022,9,1,16
4,20,20,2.941560e+03,2.941560e+03,0,1,3,9,0.0,0.0,...,3,-1,530,3,-1,530,2022,9,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12002389,54219,256398,1.549780e-01,1.549780e-01,23,10,5,9,0.0,1.0,...,-1,-1,6631,-1,-1,8711,2022,9,10,57
12002390,15,256398,1.081280e-01,1.081280e-01,23,10,5,9,0.0,1.0,...,-1,-1,8671,-1,-1,8711,2022,9,10,35
12002391,154365,256398,4.988000e-03,4.988000e-03,23,10,5,9,0.0,1.0,...,-1,-1,6771,-1,-1,8711,2022,9,10,52
12002392,256398,256398,3.841700e-02,3.841700e-02,23,10,5,9,0.0,1.0,...,-1,-1,6311,-1,-1,8711,2022,9,10,46
12002393,154518,256398,2.819830e-01,2.819830e-01,23,10,5,9,0.0,1.0,...,-1,-1,6091,-1,-1,8711,2022,9,10,37

In [12]:
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTEENN
from imblearn.under_sampling import EditedNearestNeighbours
from sklearn.utils import shuffle

# https://imbalanced-learn.org/stable/references/generated/imblearn.combine.SMOTEENN.html
def get_smoteenn():
    return SMOTEENN(
        sampling_strategy='auto',
        random_state=42,
        smote=SMOTE(k_neighbors=3, n_jobs=-1),
        enn=EditedNearestNeighbours(n_neighbors=3, n_jobs=-1),
        n_jobs=-1
    )

def batchwise_smoteenn(X, y, batch_size=200000):
    Xy_resampled_batches = []

    # Shuffle first to randomize the order
    X, y = shuffle(X, y, random_state=42)

    num_rows = len(X)
    num_batches = (num_rows + batch_size - 1) // batch_size

    for i in range(num_batches):
        print(f"Processing batch {i+1}/{num_batches}...")

        # Define batch boundaries
        start = i * batch_size
        end = min((i + 1) * batch_size, num_rows)

        X_batch = X.iloc[start:end]
        y_batch = y.iloc[start:end]

        # Apply SMOTEENN to this batch
        sme = get_smoteenn()
        try:
            X_resampled_batch, y_resampled_batch = sme.fit_resample(X_batch, y_batch)
            batch_df = pd.concat([pd.DataFrame(X_resampled_batch), pd.Series(y_resampled_batch, name='target')], axis=1)
            Xy_resampled_batches.append(batch_df)
        except Exception as e:
            print(f"Skipping batch {i+1} due to error: {e}")

    # Concatenate all batch results
    final_df = pd.concat(Xy_resampled_batches, ignore_index=True)
    return final_df.drop(columns='target'), final_df['target']


# fit_resample (X, y, **params) : Resample the dataset.
X, y = batchwise_smoteenn(X, # X : {array-like, dataframe, sparse matrix} of shape (n_samples, n_features)
                              y, # y : array-like of shape (n_samples,)
                              batch_size=200000) 

X

Processing batch 1/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(
Python(27548) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Processing batch 2/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 3/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 4/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 5/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 6/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 7/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 8/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 9/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 10/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 11/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 12/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 13/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 14/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 15/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 16/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 17/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 18/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 19/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 20/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 21/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 22/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 23/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 24/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 25/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 26/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 27/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 28/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 29/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 30/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 31/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 32/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 33/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 34/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 35/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 36/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 37/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 38/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 39/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 40/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 41/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 42/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 43/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 44/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 45/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 46/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 47/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 48/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 49/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 50/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 51/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 52/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 53/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 54/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 55/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 56/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 57/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 58/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 59/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 60/61...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

Processing batch 61/61...
Skipping batch 61 due to error: Expected n_neighbors <= n_samples,  but n_samples = 1, n_neighbors = 4

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

,From Bank,To Bank,Amount Received,Amount Paid,hour,day,weekday,month,Receiving Currency_Australian Dollar,Receiving Currency_Bitcoin,...,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num,timestamp_column_name_year,timestamp_column_name_month,timestamp_column_name_day,timestamp_column_name_minute
0,132483,132483,7.356000e+01,6.277000e+01,13,5,0,9,0.0,0.0,...,4,-1,140,4,-1,140,2022,9,5,26
1,70,1,1.394000e+02,1.394000e+02,6,1,3,9,0.0,0.0,...,1,-1,660,0,-1,990,2022,9,1,24
2,3051,114674,1.604690e+03,1.604690e+03,11,5,0,9,0.0,0.0,...,3,4,0,3,-1,250,2022,9,5,27
3,35777,136474,1.300807e+06,1.300807e+06,0,1,3,9,0.0,0.0,...,4,4,80,5,-1,540,2022,9,1,26
4,210858,225145,5.022953e+04,5.022953e+04,5,10,5,9,0.0,0.0,...,3,2,40,5,-1,870,2022,9,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23892487,47,23963,3.902932e+04,3.902932e+04,8,8,3,9,0.0,0.0,...,0,-1,2009,2,-1,2113,2022,9,8,18
23892488,219,11,1.226308e+04,1.226308e+04,2,6,1,9,0.0,0.0,...,0,1,59,0,-1,1007,2022,9,6,19
23892489,25716,1697,2.824462e+03,2.824462e+03,17,5,0,9,0.0,0.0,...,-1,-1,2647,0,-1,559,2022,9,5,21
23892490,1664,14256,3.012976e+03,3.012976e+03,6,10,5,9,0.0,0.0,...,3,0,939,-1,-1,9568,2022,9,10,31
23892491,24276,9159,7.803784e+03,7.803784e+03,9,6,5,9,0.0,0.0,...,2,0,134,4,1,58,2022,9,6,35

In [13]:
y

0           0
1           0
2           0
3           0
4           0
           ..
23892487    1
23892488    1
23892489    1
23892490    1
23892491    1
Name: target, Length: 23892492, dtype: int64

# Use OneHotEncoder for all the object datatype

In [ ]:
from scipy import sparse
from scipy.sparse import save_npz

categorical_cols = [col for col in X.select_dtypes(include='object') if col not in ['hour', 'day', 'weekday', 'month', 'Account_Grouped']]

encoder = OneHotEncoder(handle_unknown='ignore', sparse=True)
encoded_sparse = encoder.fit_transform(X[categorical_cols])

numeric_X = X.drop(columns=categorical_cols + ['hour', 'day', 'weekday', 'month', 'Account_Grouped']).select_dtypes(include=['number'])
numeric_array = numeric_X.to_numpy()

X_final_sparse = sparse.hstack([encoded_sparse, numeric_array], format='csr')

save_npz("X_final_sparse.npz", X_final_sparse)

In [ ]:
# from scipy.sparse import load_npz

X_final_sparse = load_npz("X_final_sparse.npz")
print(X_final_sparse.shape)  # Just to confirm it loaded correctly

In [ ]:

X_final_sparse = load_npz("X_final_sparse.npz")
print(X_final_sparse.shape)  # Just to confirm it loaded correctly

In [ ]:
import pandas as pd

# Load a few rows only (e.g., first 5)
sample_dense = X_final_sparse[:100].toarray()

# If you saved the encoder earlier:
# encoder.get_feature_names_out(categorical_cols) + numeric column names
# Otherwise, use placeholder column names:
column_names = [f'col_{i}' for i in range(sample_dense.shape[1])]

# Convert to DataFrame
sample_df = pd.DataFrame(sample_dense, columns=column_names)

# View it
display(sample_df.head())

# Pearson Co-relation.

In [ ]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import sparse
from sklearn.preprocessing import OneHotEncoder

y_array = y.to_numpy()

# ----- Step 2: Compute Pearson Correlation (Sparse-Safe) -----
correlations = []
for i in tqdm(range(X_final_sparse.shape[1]), desc="Calculating Pearson correlation"):
    col = X_final_sparse.getcol(i).toarray().ravel()
    if np.std(col) == 0:
        corr = 0
    else:
        corr = np.corrcoef(col, y_array)[0, 1]
    correlations.append(corr)

# ----- Step 3: Prepare Results -----
encoded_feature_names = encoder.get_feature_names_out(categorical_cols)
all_feature_names = list(encoded_feature_names) + list(numeric_X.columns)

corr_df = pd.DataFrame({
    'feature': all_feature_names,
    'correlation': correlations
}).dropna()

In [ ]:
top_100 = corr_df.reindex(corr_df['correlation'].abs().sort_values(ascending=False).index).head(100)

# ----- Step 4: Plot -----
plt.figure(figsize=(12, 18))
sns.barplot(data=top_100, y='feature', x='correlation', palette='coolwarm')
plt.axvline(0, color='black', linewidth=0.5)
plt.title('Top 100 Pearson Correlated Features with Target (Is Laundering)')
plt.tight_layout()
plt.show()